server:
  port: 8080

spring:
  application:
    name: demo1
  profiles:
    active: dev
    include: secret
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

logging:
  level:
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  dev:
    domain: localhost
    backUrl: "http://${custom.dev.domain}:${server.port}"
    frontUrl: "http://${custom.dev.domain}:3000"
  prod:
    domain: app3.qwas.shop
    backUrl: "https://api.${custom.prod.domain}"
    frontUrl: "https://www.${custom.prod.domain}"
  site:
    domain: "${custom.dev.domain}"
    backUrl: "${custom.dev.backUrl}"
    frontUrl: "${custom.dev.frontUrl}"